### PR TITLE
ROVER-119: Linting and Formatting Workflow Configured

### PR DESCRIPTION
**Pull request by noodlekid**
This pull request adds a new GitHub Actions workflow to ensure code quality by performing linting and formatting checks for both Python and JavaScript/TypeScript files. The most important changes include the configuration of the workflow and the specific steps for each language.

GitHub Actions workflow configuration:

* [`.github/workflows/lint-and-format.yml`](diffhunk://#diff-60395b39061839b3177416592202e101e3e9d52394ab5d27ed094d4e771f0245R1-R36): Added a new workflow named "Lint and Format Check" that triggers on push and pull request events for all branches.

Python linting and formatting:

* [`.github/workflows/lint-and-format.yml`](diffhunk://#diff-60395b39061839b3177416592202e101e3e9d52394ab5d27ed094d4e771f0245R1-R36): Added steps to install Python dependencies, run Black for formatting checks, and run Pylint for linting checks with a configurable score threshold.

JavaScript/TypeScript linting and formatting:

* [`.github/workflows/lint-and-format.yml`](diffhunk://#diff-60395b39061839b3177416592202e101e3e9d52394ab5d27ed094d4e771f0245R1-R36): Added steps to install Node.js dependencies, run Prettier for formatting checks, and run ESLint for linting checks.

### CODE REVIEW

**Comment by noodlekid** [comment]
Right now formatting is not enforced and simply checked, but it can be set to strictly format and lint on each PR and push.

**Review by ConnorNeed — COMMENTED** [review]
LGTM. Do the current files pass the PyLint? If not we want to make those changes first while the codebase is small

**Comment by noodlekid** [comment]
@ConnorNeed You can already see the tests working! Almost all the python fails the black formatting, I will set it to forcefully format so it will always pass this step, linting will be checked after formatting.

**Comment by noodlekid** [comment]
Just realized you cant do that. We need a precommit hook to run formatting on push or pull I believe.

**Comment by ConnorNeed** [comment]
Lgtm. Squash commits on merge? I'd like to keep a cleaner history this time around

**Review by ConnorNeed — APPROVED** [review]

**Pull request merged**
