### PR TITLE
Add elevation_mapping, kindr_ros and zed ros2 wrapper repos

### PR DESCRIPTION
**Pull request by ErikCald**
This PR adds 3 git sub modules:
- My own fork of the elevation_mapping repo from Anybotics, but using the version from Muhammad540 and others who ported it to ros2
- The kindr_ros repo since the elevation_mapping is dependent on it
- The zed ros2 wrapper

I'm not sure the desired directory structure we want, I'm open to moving these around if it's possible. The elevation_mapping and kindr_ros repos fit under localization. 

The zed ros2 wrapper should exist on its own since I think it will be used by more things.

Image of what the elevation_mapping produces:
Screenshot from 2024-11-27 23-42-58

### CODE REVIEW

**Comment by ConnorNeed** [comment]
For https://jira.engsoc.net/browse/ROVER-307

**Review by ConnorNeed — APPROVED** [review]
LGTM

**Review by ChrisRusu1 — APPROVED** [review]
LGTM Connor was saying we might move the submodules into their own folder later, but for now its aight

**Comment by ErikCald** [comment]
I found a config file for grid maps to calculate traversibility based on the elevation using gridmaps filters. File below:
https://github.com/ANYbotics/grid_map/blob/master/grid_map_demos/config/filters_demo_filter_chain.yaml

I ported this config to ros2 and fixed a few of the parameters up and removed the inpaint filter because it was crashing with my opencv version. This is what it looks like now (colour represents traversiblity)
Screenshot from 2024-12-03 22-20-34
Screenshot from 2024-12-03 22-16-09

**Comment by ConnorNeed** [comment]
This looks significantly better than I was even hoping for. Would love to see this with more testing on gentle slopes. Are you okay with me adding one of these images to our round table tonight? This is huge!

**Comment by ErikCald** [comment]
@ConnorNeed yep feel free to use those images. I have a few more in a google drive here too: https://drive.google.com/drive/folders/1ALqf_S9XxZ0g1MT27mcr_8bd7EsBaCTX?usp=drive_link

**Comment by ConnorNeed** [comment]
@ErikCald Go ahead and merge if it's ready. I don't want PRs to get stale as that is a sure fire way to end up with conflicts.

**Pull request merged**
